//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gruppa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Gruppa()
        {
            this.LessonPlan = new HashSet<LessonPlan>();
            this.Student = new HashSet<Student>();
        }
    
        public int GruppaID { get; set; }
        public string GruppaName { get; set; }
        public int SpecialID { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime FinishDate { get; set; }
        public bool Active { get; set; }
    
        public virtual Special Special { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonPlan> LessonPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
    }
}
