//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeApp
{    
    public partial class Schedule
    {
        public int ScheduleID { get; set; }
        public int LessonPlanID { get; set; }
        public byte DayID { get; set; }
        public byte ClassroomID { get; set; }
        public byte LessonNumId { get; set; }
        public virtual Classroom Classroom { get; set; }
        public virtual Day Day { get; set; }
        public virtual LessonNum LessonNum { get; set; }
        public virtual LessonPlan LessonPlan { get; set; }
    }
}
