//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int UserID { get; set; }
        public int GruppaID { get; set; }
        public string Zachetka { get; set; }
    
        public virtual Gruppa Gruppa { get; set; }
        public virtual User User { get; set; }
    }
}
