//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.LessonPlan = new HashSet<LessonPlan>();
        }

        public string FullName => $"{Surname} {Name} {LastName}";

        public string IsActive => Active ? "Активен" : "Заблокирован";

        public int UserID { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public byte GenderID { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public byte RoleID { get; set; }
        public byte[] UserPhoto { get; set; }
        public bool Active { get; set; }
   

        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LessonPlan> LessonPlan { get; set; }
        public virtual Role Role { get; set; }
        public virtual Student Student { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
